Do test code coverage

diff --git a/hello/test b/hello/test
--- a/hello/test
+++ b/hello/test
@@ -1,3 +1,20 @@
 #!/bin/bash
 
 if [[ ! -f main ]]; then exit 1; fi
+
+##########################################
+# Test debug version
+##########################################
+make debug
+./main
+
+#####################
+# Test code coverage
+#####################
+
+n=`gcov-7 -i -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
+if [ ! "$n" -eq "1" ]; then
+  echo "Error: must have 100% code coverage. Current code coverage:"
+  gcov-7 -i -n -o debug main.cpp | head -n 2 | tail -n 1
+  exit 1
+fi
